// <auto-generated />
using System;
using ChangeOrder.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangeOrder.Data.Migrations
{
    [DbContext(typeof(ChangeOrderDbContext))]
    [Migration("20260620175421_AddIdempotencyRecords")]
    partial class AddIdempotencyRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChangeOrder.Domain.Entities.ChangeOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InitialEvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostDeployScreenshotPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ProductionDeployDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductionVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionScreenshotPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ChangeOrders", (string)null);
                });

            modelBuilder.Entity("ChangeOrder.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Key");

                    b.HasIndex("CreatedAt");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("ChangeOrder.Domain.Entities.ChangeOrderEntity", b =>
                {
                    b.OwnsOne("ChangeOrder.Domain.ValueObjects.ApprovalChain", "Approval", b1 =>
                        {
                            b1.Property<Guid>("ChangeOrderEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DepartmentHeadApproval")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("ItHeadApproval")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("ProgrammingDivisionApproval")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("RequesterApproval")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("ChangeOrderEntityId");

                            b1.ToTable("ChangeOrders");

                            b1.WithOwner()
                                .HasForeignKey("ChangeOrderEntityId");
                        });

                    b.OwnsOne("ChangeOrder.Domain.ValueObjects.OrderNumber", "Number", b1 =>
                        {
                            b1.Property<Guid>("ChangeOrderEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("nvarchar(13)")
                                .HasColumnName("OrderNumber");

                            b1.HasKey("ChangeOrderEntityId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ChangeOrders");

                            b1.WithOwner()
                                .HasForeignKey("ChangeOrderEntityId");
                        });

                    b.OwnsOne("ChangeOrder.Domain.ValueObjects.RequesterInfo", "Requester", b1 =>
                        {
                            b1.Property<Guid>("ChangeOrderEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Department")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("ChangeOrderEntityId");

                            b1.ToTable("ChangeOrders");

                            b1.WithOwner()
                                .HasForeignKey("ChangeOrderEntityId");
                        });

                    b.Navigation("Approval")
                        .IsRequired();

                    b.Navigation("Number")
                        .IsRequired();

                    b.Navigation("Requester")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
