// <auto-generated />
using System;
using ChangeOrder.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChangeOrder.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChangeOrder.Domain.Entities.ChangeOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InitialEvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PostDeployScreenshotPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ProductionDeployDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductionVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RequiredAction")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionScreenshotPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ChangeOrders_IsDeleted");

                    b.HasIndex("RequestDate")
                        .HasDatabaseName("IX_ChangeOrders_RequestDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ChangeOrders_Status");

                    b.ToTable("ChangeOrders", "dbo");
                });

            modelBuilder.Entity("ChangeOrder.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)");

                    b.HasKey("Key");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_IdempotencyKeys_CreatedAt");

                    b.HasIndex("OrderId");

                    b.ToTable("IdempotencyKeys", "dbo");
                });

            modelBuilder.Entity("ChangeOrder.Domain.Entities.ChangeOrder", b =>
                {
                    b.OwnsOne("ChangeOrder.Domain.ValueObjects.ApprovalChain", "ApprovalChain", b1 =>
                        {
                            b1.Property<Guid>("ChangeOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DepartmentHeadApproval")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasDefaultValue("Pending")
                                .HasColumnName("Approval_DepartmentHead");

                            b1.Property<string>("ItHeadApproval")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasDefaultValue("Pending")
                                .HasColumnName("Approval_ItHead");

                            b1.Property<string>("ProgrammingDivisionApproval")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasDefaultValue("Pending")
                                .HasColumnName("Approval_ProgrammingDivision");

                            b1.Property<string>("RequesterApproval")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasDefaultValue("Pending")
                                .HasColumnName("Approval_Requester");

                            b1.HasKey("ChangeOrderId");

                            b1.ToTable("ChangeOrders", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ChangeOrderId");
                        });

                    b.OwnsOne("ChangeOrder.Domain.ValueObjects.OrderNumber", "OrderNumber", b1 =>
                        {
                            b1.Property<Guid>("ChangeOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(13)")
                                .HasColumnName("OrderNumber");

                            b1.HasKey("ChangeOrderId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_ChangeOrders_OrderNumber");

                            b1.ToTable("ChangeOrders", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ChangeOrderId");
                        });

                    b.OwnsOne("ChangeOrder.Domain.ValueObjects.RequesterInfo", "Requester", b1 =>
                        {
                            b1.Property<Guid>("ChangeOrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Department")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Requester_Department");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Requester_Email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Requester_Name");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Requester_Position");

                            b1.HasKey("ChangeOrderId");

                            b1.ToTable("ChangeOrders", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ChangeOrderId");
                        });

                    b.Navigation("ApprovalChain")
                        .IsRequired();

                    b.Navigation("OrderNumber")
                        .IsRequired();

                    b.Navigation("Requester")
                        .IsRequired();
                });

            modelBuilder.Entity("ChangeOrder.Domain.Entities.IdempotencyKey", b =>
                {
                    b.HasOne("ChangeOrder.Domain.Entities.ChangeOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
