<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoWarn>$(NoWarn);CS9137</NoWarn>
        <!-- Habilita el espacio de nombres requerido por el generador de OpenAPI -->
        <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="Properties\launchSettings.json" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Http" Version="10.0.0" />
        <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.3" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ChangeOrder.Data\ChangeOrder.Data.csproj" />
        <ProjectReference Include="..\ChangeOrder.Presentation\ChangeOrder.Presentation.csproj" />
    </ItemGroup>

</Project>
